### ISSUE TITLE
chroma key mode for the repl

### ISSUE THREAD

**Issue by geikha** [tidalcycles/strudel#939]
sometimes I do the following in Pulsar so that a visualist can project their visuals with my code on top (or use the code as part of the visuals) [you can send the same video signal of your screen through HDMI or NDI]

```css
atom-text-editor span {
  background-color: black;
}

atom-text-editor {
 background-color: #0f0;
}
```

How can I do this in strudel? Maybe we could add a "chroma key mode" for these scenarios (line background turns to the actual theme's background, editor background goes #00ff00)

![image](https://github.com/tidalcycles/strudel/assets/56176668/4f86b3dd-269b-4061-9eb7-5ff56722b853)

---

> Good idea, this could just be a new theme. - @felixroos on Discord

Should it tho? What if you want to keep the text colors but just change the editor background as shown in the image?
